#!/bin/sh

if [ "$(uci -q get luci.diag)" != "internal" ]; then
	host="sensecapmx.com"

	uci -q batch <<-EOF >/dev/null
		set luci.diag=internal
		set luci.diag.dns='${host:-openwrt.org}'
		set luci.diag.ping='${host:-openwrt.org}'
		set luci.diag.route='${host:-openwrt.org}'
		commit luci
	EOF
fi

exit 0
