#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.SenseCAP >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.SenseCAP=/luci-static/sensecap
		set luci.main.mediaurlbase=/luci-static/sensecap
		commit luci
	EOF
fi

exit 0
