#!/bin/sh /etc/rc.common
START=96
STOP=14

USE_PROCD=1
PROG=/usr/bin/lte-serve

LTE_POWER_PIN=480

start_service()
{
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn 3600 60 60
	procd_close_instance
}

stop_service() {
	local pid=`pgrep -f "quectel-CM"`
	if [ -n "$pid" ]; then
		kill -9 $pid
	fi
	echo "0" > /sys/class/gpio/gpio${LTE_POWER_PIN}/value
}

service_triggers()
{
	procd_add_reload_trigger "lte_config"
}

reload_service()
{
	stop
	start
}
