include $(TOPDIR)/rules.mk

LUCI_TITLE:=ChirpStack Concentratord (Seeed Gateway)
LUCI_DEPENDS:=+luci-base +luci-app-chirpstack-concentratord
PKG_MAINTAINER:=ruiqian tang <ruiqian.tang@seeed.cc>
PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
