#!/bin/sh

if [ -e "/etc/config/lora" ]; then
	REGION=$(uci get lora.radio.region)
	FREQ_PLAN=$(uci get lora.radio.channel_plan)
	
	if [ -n "$REGION" -a -n "$FREQ_PLAN" ];then
		exit 0
	fi
else 
	touch /etc/config/lora_radio
fi

if [ -e "/etc/deviceinfo/loraModem" ]; then
	region=$(cat /etc/deviceinfo/loraModem)
	case "$region" in
		"915" | "US915") REGION_MODEM="US915"; FREQ_PLAN="US_902_928_FSB_1";;
		"868" | "EU868") REGION_MODEM="EU868"; FREQ_PLAN="EU_863_870_TTN";;
		"AU915") REGION_MODEM="AU915"; FREQ_PLAN="AU_915_928_FSB_1";;
		*) REGION_MODEM="US915";  FREQ_PLAN="US_902_928_FSB_1";;
	esac
else
	REGION_MODEM="US915";  FREQ_PLAN="US_902_928_FSB_1"
fi

uci set lora.radio.region="$REGION_MODEM"
uci set lora.radio.channel_plan="$FREQ_PLAN"

uci commit lora.radio


exit 0