include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI UPS Configuration
LUCI_DEPENDS:=+luci-base +ups-module
PKG_MAINTAINER:= Ruiqian Tang <ruiqian.tang@seeed.cc>
PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
